name = "TussleCraft"
author = "devJordan"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1083cc48bde52764a465f812b17235c5252eeed61f14892ffabd6d91924ab580"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
